name: Update Advent of Code calendar

on:
  schedule:
    - cron: '1 5 1-25 12 *'
  workflow_dispatch:

jobs:
  update_calendar:
    name: Update calendar
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Get current date
        shell: bash
        run: echo "day=$(date +%-d)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch puzzle input and prompt
        uses: docker://ghcr.io/edoardob90/aoc-py-template:latest
        with:
          args: "2023 ${{ env.day }}"
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION_TOKEN }}

      - name: Push to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Day ${{ env.day }}"
